config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#party'

  resources :publications, only: %i[index show]
  resources :membership_requests, only: %i[new create]

  get :party, to: 'pages#party'
  get :libertarianism, to: 'pages#libertarianism'
  get :join, to: 'membership_requests#new'
  get :donate, to: 'pages#donate'

  get :platform, to: 'pages#platform'
  get :press, to: 'pages#press'
  get :success, to: 'pages#success'

  get :login, to: 'admin/sessions#new'
  post :logout, to: 'admin/sessions#destroy'

  namespace :admin do
    root 'pages#home'

    resources :publications, except: :show
    resources :users, except: :show do
      resource :password, only: %i[edit update]
    end
    resources :invites, except: %i[edit update]

    resources :sessions, only: %i[new create destroy]
    resources :password_resets, only: %i[new create]
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < Publication
end

app/views/articles/_article.html.erb
<li>
  <article class="card">
    <%= link_to publication_path(article) do %>
      <%= image_tag url_for(article.picture.file), class: 'card-image' %>
    <% end %>

    <h3 class="card-title">
      <%= link_to article.title, publication_path(article) %>
    </h3>

    <%= link_to publication_path(article) do %>
      <p class="card-content">
        <%= article.annotation %>
      </p>
    <% end %>

    <footer class="wrappable-layout">
      <div class="card-label">
        <%= article.model_name.human %>
      </div>
      <div class="card-label">
        <%= time_tag article.published_at,
              time_ago_in_words_or_short_date(article.published_at) %>
      </div>
    </footer>
  </article>
</li>