config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#party'

  resources :publications, only: %i[index show]
  resources :membership_requests, only: %i[new create]

  get :party, to: 'pages#party'
  get :libertarianism, to: 'pages#libertarianism'
  get :join, to: 'membership_requests#new'
  get :donate, to: 'pages#donate'

  get :platform, to: 'pages#platform'
  get :press, to: 'pages#press'
  get :success, to: 'pages#success'

  get :login, to: 'admin/sessions#new'
  post :logout, to: 'admin/sessions#destroy'

  namespace :admin do
    root 'pages#home'

    resources :publications, except: :show
    resources :users, except: :show do
      resource :password, only: %i[edit update]
    end
    resources :invites, except: %i[edit update]

    resources :sessions, only: %i[new create destroy]
    resources :password_resets, only: %i[new create]
  end
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  has_one :user

  def fresh?
    !expired? && !used?
  end

  def expired?
    created_at.present? && created_at < 12.hours.ago
  end

  def used?
    user.present?
  end
end

app/controllers/admin/invites_controller.rb
# frozen_string_literal: true

module Admin
  class InvitesController < BaseController
    before_action :require_admin
    before_action :set_invite, only: %i[show destroy]

    def index
      @invites = Invite.reorder(created_at: :desc).page(params[:page]).per(9)
    end

    def show
    end

    def new
      @invite = Invite.new
    end

    def create
      @invite = Invite.new(invite_params)

      if @invite.save
        redirect_to admin_invite_url(@invite), notice: t('.success')
      else
        render :new
      end
    end

    def destroy
      @invite.destroy
      redirect_to admin_invites_url, notice: t('.success')
    end

    private

    def set_invite
      @invite = Invite.find(params[:id])
    end

    def invite_params
      params.require(:invite).permit(:comment)
    end
  end
end

app/views/admin/invites/_form.html.erb
<%= form_with model: [:admin, invite],
      local: true,
      class: 'box',
      id: 'invite-form' do |form| %>

  <%= render 'shared/errors', obj: invite %>

  <div class="field">
    <%= form.label :comment, class: 'label' %>
    <div class="control">
      <%= form.text_field :comment, id: :invite_comment, class: 'input' %>
    </div>
  </div>
<% end %>

app/views/admin/invites/index.html.erb
<div class="container">
  <section class="actions">
    <div class="level">
      <div class="level-left">
        <h1 class="title is-4 has-text-white"><%= t('.invites') %></h1>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to t('.generate'), new_admin_invite_path, class: 'button' %>
        </div>
      </div>
    </div>
  </section>

  <section class="list">
   <div class="list-header">
      <div class="columns is-mobile">
        <div class="column is-two-thirds">
          <span><%= Invite.human_attribute_name(:id) %></span>
        </div>
        <div class="column is-one-third">
          <span><%= Invite.human_attribute_name(:created_at) %></span>
        </div>
      </div>
    </div>

    <div class="list-items">
      <% @invites.each do |invite| %>
        <%= link_to admin_invite_path(invite), class: 'list-item' do %>
          <div class="columns is-mobile">
            <div class="column is-two-thirds">
              <span><%= invite.id %></span>
            </div>
            <div class="column is-one-third">
              <span><%= l(invite.created_at, format: :long) %></span>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>

  <%= paginate @invites, views_prefix: 'admin' %>
</div>

app/views/admin/invites/new.html.erb
<div class="container">
  <section class="actions">
    <div class="level">
      <div class="level-left">
        <h1 class="title is-4 has-text-white"><%= t('.generate_invite') %></h1>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= submit_tag t('save'), form: 'invite-form', class: 'button' %>
        </div>
      </div>
    </div>
  </section>

  <%= render 'form', invite: @invite %>
</div>

app/views/admin/invites/show.html.erb
<div class="container">
  <section class="actions">
    <div class="level">
      <div class="level-left">
        <h1 class="title is-4 has-text-white">
          <%= Invite.model_name.human %>
        </h1>
      </div>
      <div class="level-right">
        <%= link_to t('delete'),
              admin_invite_path(@invite),
              class: 'button is-danger',
              method: :delete,
              data: {confirm: t('are_you_sure')} %>
      </div>
    </div>
  </section>

  <div class="box">
    <% if @invite.used? %>
      <div class="columns">
        <div class="column is-one-quarter has-text-weight-bold">
          <%= User.model_name.human %>
        </div>
        <div class="column">
          <%= link_to @invite.user.name, edit_admin_user_path(@invite.user) %>
        </div>
      </div>
    <% else %>
      <div class="columns">
        <div class="column is-one-quarter has-text-weight-bold">
          <%= t('.registration_link') %>
        </div>
        <div class="column">
          <%= link_to nil, new_admin_user_url(invite: @invite.id) %>
        </div>
      </div>
    <% end %>

    <div class="columns">
      <div class="column is-one-quarter has-text-weight-bold">
        <%= Invite.human_attribute_name(:comment) %>
      </div>
      <div class="column">
        <%= @invite.comment %>
      </div>
    </div>

    <div class="columns">
      <div class="column is-one-quarter has-text-weight-bold">
        <%= Invite.human_attribute_name(:created_at) %>
      </div>
      <div class="column">
        <%= l(@invite.created_at, format: :long) %>
      </div>
    </div>
  </div>
</div>