config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#party'

  resources :publications, only: %i[index show]
  resources :membership_requests, only: %i[new create]

  get :party, to: 'pages#party'
  get :libertarianism, to: 'pages#libertarianism'
  get :join, to: 'membership_requests#new'
  get :donate, to: 'pages#donate'

  get :platform, to: 'pages#platform'
  get :press, to: 'pages#press'
  get :success, to: 'pages#success'

  get :login, to: 'admin/sessions#new'
  post :logout, to: 'admin/sessions#destroy'

  namespace :admin do
    root 'pages#home'

    resources :publications, except: :show
    resources :users, except: :show do
      resource :password, only: %i[edit update]
    end
    resources :invites, except: %i[edit update]

    resources :sessions, only: %i[new create destroy]
    resources :password_resets, only: %i[new create]
  end
end

app/models/publication.rb
# frozen_string_literal: true

class Publication < ApplicationRecord
  VALID_TYPES = %w[Article News Statement].freeze

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_one :picture, as: :picturable, dependent: :destroy

  accepts_nested_attributes_for :picture

  validates :annotation, presence: true, length: {maximum: 140}
  validates :author, presence: true
  validates :body, presence: true
  validates :picture, presence: true
  validates :published_at, presence: true
  validates :title, presence: true
  validates :type, inclusion: {in: VALID_TYPES}

  def self.types
    VALID_TYPES
  end
end

app/controllers/admin/publications_controller.rb
# frozen_string_literal: true

module Admin
  class PublicationsController < BaseController
    before_action :set_publication, only: %i[edit update destroy]

    def index
      @publications = Publication
                      .reorder(created_at: :desc)
                      .page(params[:page])
                      .per(9)
    end

    def new
      return unless publication_type

      @publication = publication_type.constantize.new
      @publication.build_picture
    end

    def create
      @publication = publication_type.constantize.new(publication_params)
      @publication.author = current_user

      if @publication.save
        redirect_to admin_publications_url, notice: t('.success')
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @publication.update(publication_params)
        redirect_to admin_publications_url, notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @publication.destroy
      redirect_to admin_publications_url, notice: t('.success')
    end

    private

    def set_publication
      @publication = Publication.find(params[:id])
    end

    def publication_type
      @publication_type ||= params[:type] if params[:type].in?(Publication.types)
    end

    def publication_params
      params
        .require(publication_type.downcase)
        .permit(
          :annotation,
          :body,
          :published_at,
          :title,
          picture_attributes: [:file]
        )
    end
  end
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

class PublicationsController < ApplicationController
  def index
    @publications = Publication
                    .reorder(published_at: :desc)
                    .page(params[:page])
                    .per(9)
  end

  def show
    @publication = Publication.find(params[:id])
  end
end

app/views/admin/publications/edit.html.erb
<div class="container">
  <section class="actions">
    <div class="level">
      <div class="level-left">
        <h1 class="title is-4 has-text-white"><%= t('.edit_publication') %></h1>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= submit_tag t('save'), form: 'publication-form', class: 'button' %>
        </div>
        <div class="level-item">
          <%= link_to t('delete'),
                admin_publication_path(@publication),
                class: 'button is-danger',
                method: :delete,
                data: {confirm: t('are_you_sure')} %>
        </div>
      </div>
    </div>
  </section>

  <%= form_with model: [:admin, @publication],
        url: admin_publication_path(@publication),
        local: true,
        class: 'box',
        id: 'publication-form' do |form| %>

    <%= render 'shared/errors', obj: @publication %>
    <%= render "admin/#{@publication.type.downcase.pluralize}/fields",
          form: form %>
  <% end %>
</div>

app/views/admin/publications/index.html.erb
<div class="container">
  <section class="actions">
    <div class="level">
      <div class="level-left">
        <h1 class="title is-4 has-text-white"><%= t('.publications') %></h1>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to t('.add'), new_admin_publication_path, class: 'button' %>
        </div>
      </div>
    </div>
  </section>

  <section class="list">
    <div class="list-header">
      <div class="columns is-mobile">
        <div class="column is-two-thirds">
          <span><%= Publication.human_attribute_name(:title) %></span>
        </div>
        <div class="column is-one-third">
          <span><%= Publication.human_attribute_name(:published_at) %></span>
        </div>
      </div>
    </div>

    <div class="list-body">
      <% @publications.each do |publication| %>
        <%= link_to edit_admin_publication_path(publication),
              class: 'list-item' do %>
          <div class="columns is-mobile">
            <div class="column is-two-thirds">
              <span><%= publication.title %></span>
            </div>
            <div class="column is-one-third">
              <span><%= l(publication.published_at, format: :long) %></span>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>

  <%= paginate @publications, views_prefix: 'admin' %>
</div>

app/views/admin/publications/new.html.erb
<% if @publication %>
  <div class="container">
    <section class="actions">
      <div class="level">
        <div class="level-left">
          <h1 class="title is-4 has-text-white">
            <%= t('.add_publication') %>
          </h1>
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= submit_tag t('save'),
                  form: 'publication-form',
                  class: 'button' %>
          </div>
        </div>
      </div>
    </section>

    <%= form_with model: [:admin, @publication],
          url: admin_publications_path,
          local: true,
          class: 'box',
          id: 'publication-form' do |form| %>

      <%= render 'shared/errors', obj: @publication %>
      <%= render "admin/#{@publication.type.downcase.pluralize}/fields",
            form: form %>
    <% end %>
  </div>
<% else %>
  <div class="columns">
    <div class="column is-one-third is-offset-one-third">
      <br>
      <h1 class="title"><%= t('.choose_type') %></h1>
      <div class="buttons">
        <% Publication.types.each do |type| %>
          <%= link_to type.constantize.model_name.human,
                new_admin_publication_path(type: type),
                class: 'button' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>